### ISSUE TITLE
Incompatible with Gorm V2

### ISSUE THREAD

**Issue by ping-localhost** [qor/transition#17]
This library is currently not compatible with Gorm v2. I've tried to create a PR, but I don't understand what should be used instead of `NewScope` or `tx.New()`, so I'm unable to rewrite his for the new version.

Could someone look into this and release an updated version? Thank you.

/cc @jinzhu

**Comment by jinzhu** [comment]
https://gorm.io/docs/write_plugins.html

**Comment by joykk** [comment]
me too
