### ISSUE TITLE
Dependency on gorm

### ISSUE THREAD

**Issue by falzm** [qor/transition#2]
Hi

I'd love to use this package, however the dependency on `gorm` package (and thus its own dependencies) too much of a baggage... Is there any way to make it gorm-independant?

**Comment by jinzhu** [comment]
Hi @falzm 

I think this is not a big deal, it just make your binary a little bigger if you don't use gorm?

But if remove the gorm dependence, it is hard to bring in the state change logs feature then.

Thank you.

**Comment by falzm** [comment]
This is more related to package vendoring: gorm and its own dependencies add **a lot** of code to projects vendoring your package...
