### ISSUE TITLE
Not useable as a standalone without GORM

### ISSUE THREAD

**Issue by duncanhall** [qor/transition#9]
The definitions for the Enter and Exit functions have the following the signatures:

```
func (state *State) Enter(fc func(value interface{}, tx *gorm.DB) error) *State
func (state *State) Exit(fc func(value interface{}, tx *gorm.DB) error) *State
```

As the second argument is explicitly typed as a `gorm.DB` pointer, there is no way to implement these functions without import the `gorm` package.

**Comment by jwreagor** [comment]
I enjoy the core functionality but also do not want GORM or unnecessary dependencies imported into my projects. I've created a fork over here that rips out the database functionality and includes passing tests.

I'll gladly port any patches that come up if other folks find issues.

https://github.com/cheapRoc/transition
